package com.pcfutbolmania.pcf2001.model.player;

import java.util.HashMap;
import java.util.Map;

public enum Position {

	// @formatter:off
	NONE,
	GOALKEEPER,
	RIGHT_BACK,
	LEFT_BACK,
	LIBERO,
	LEFT_CENTRE_BACK,
	RIGHT_CENTRE_BACK,
	RIGHT_MIDFIELD,
	RIGHT_CENTRAL_MIDFIELD,
	STRIKER,
	CENTRAL_MIDFIELD,
	LEFT_MIDFIELD,
	RIGHT_WING,
	ATTACKING_MIDFIELD,
	LEFT_WING,
	DEFENSIVE_MIDFIELD,
	RIGHT_ATTACKING_MIDFIELD,
	LEFT_ATTACKING_MIDFIELD,
	LEFT_CENTRAL_MIDFIELD;
	// @formatter:on

	private static final Map<Integer, Position> POSITIONS = new HashMap<>();

	static {
		POSITIONS.put(NONE.ordinal(), NONE);
		POSITIONS.put(GOALKEEPER.ordinal(), GOALKEEPER);
		POSITIONS.put(RIGHT_BACK.ordinal(), RIGHT_BACK);
		POSITIONS.put(LEFT_BACK.ordinal(), LEFT_BACK);
		POSITIONS.put(LIBERO.ordinal(), LIBERO);
		POSITIONS.put(LEFT_CENTRE_BACK.ordinal(), LEFT_CENTRE_BACK);
		POSITIONS.put(RIGHT_CENTRE_BACK.ordinal(), RIGHT_CENTRE_BACK);
		POSITIONS.put(RIGHT_MIDFIELD.ordinal(), RIGHT_MIDFIELD);
		POSITIONS.put(RIGHT_CENTRAL_MIDFIELD.ordinal(), RIGHT_CENTRAL_MIDFIELD);
		POSITIONS.put(STRIKER.ordinal(), STRIKER);
		POSITIONS.put(CENTRAL_MIDFIELD.ordinal(), CENTRAL_MIDFIELD);
		POSITIONS.put(LEFT_MIDFIELD.ordinal(), LEFT_MIDFIELD);
		POSITIONS.put(RIGHT_WING.ordinal(), RIGHT_WING);
		POSITIONS.put(ATTACKING_MIDFIELD.ordinal(), ATTACKING_MIDFIELD);
		POSITIONS.put(RIGHT_WING.ordinal(), RIGHT_WING);
		POSITIONS.put(ATTACKING_MIDFIELD.ordinal(), ATTACKING_MIDFIELD);
		POSITIONS.put(LEFT_WING.ordinal(), LEFT_WING);
		POSITIONS.put(DEFENSIVE_MIDFIELD.ordinal(), DEFENSIVE_MIDFIELD);
		POSITIONS.put(RIGHT_ATTACKING_MIDFIELD.ordinal(), RIGHT_ATTACKING_MIDFIELD);
		POSITIONS.put(LEFT_ATTACKING_MIDFIELD.ordinal(), LEFT_ATTACKING_MIDFIELD);
		POSITIONS.put(LEFT_CENTRAL_MIDFIELD.ordinal(), LEFT_CENTRAL_MIDFIELD);
	}

	public static Position valueOf(int id) {
		return POSITIONS.get(id) == null ? NONE : POSITIONS.get(id);
	}
}
